### ISSUE TITLE
File Sorting (by size)

### ISSUE THREAD

**Issue by only1pj** [mrbeam/OctoPrint#21]
Version: 1.2.0-dev-610-g4736d74 (mrbeam-stable branch)

Sorting in the design library by "Sort by file size (descending)" does not order correctly.
Incorrectly reported file size? or Sort not working.

Viewing code and design files at once - unsorted
Viewing code files only - unsorted
Viewing design files only - unsorted

Sort by Date and name seems to be ok.

**Comment by mrbeam** [comment]
done!
