### ISSUE TITLE
manually filled areas have gaps

### ISSUE THREAD

**Issue by mrbeam** [mrbeam/OctoPrint#29]
![ergebnis - svg](https://cloud.githubusercontent.com/assets/9049256/8185870/1b5acbb8-1447-11e5-968f-eefdf3dc0a18.jpg)

whatever may be the reason.
First step: check gcode creation and repeatability.

**Comment by Dregbaer** [comment]
![lines](https://cloud.githubusercontent.com/assets/12952717/8232416/da932f32-15cf-11e5-8081-a034a3417919.JPG)
It seems like it isn't skipping paths, but putting them at wrong places

**Comment by only1pj** [comment]
I used this cookie cutter method to generate a SVG and although it did run for a few hours, I knocked the material while it was burning so cancelled the job. 
I didnt have any issues with missing areas.
That one in the ladt image looks quite bad.

**Comment by hungerpirat** [comment]
Did you check if your axes are loose or the timing belt has backlash?
It looks like this happens if the axis orthogonal to the filling lines
changes direction.

Can you confirm that?

**Comment by Dregbaer** [comment]
Indeed my axes were a bit loose and the timing belt was scratching at the plastic parts. Fixed this and tried to prnt again. It made some mistakes at the beginning, 
![img_4228](https://cloud.githubusercontent.com/assets/12952717/8236111/68fb1fee-15e6-11e5-938c-782989cf8877.JPG)
but then printed everything where it belonges.
![img_4229](https://cloud.githubusercontent.com/assets/12952717/8236119/7512ad06-15e6-11e5-8725-72bce9fb1b4a.JPG)
I'll run some more tests, but already consider my problem solved.
So thanks for helping me!

**Comment by mrbeam** [comment]
You're welcome.

try to loosen the maden screws of the pulleys that they can freely spin
over the motor shaft.
Then move the gantry along the axes and try to feel if there is different
friction in some areas.
If yes, look at the rods , check the linear bearings and their seals, maybe
put a drop oil on the rods.
That should help.



2015-06-18 18:18 GMT+02:00 Dregbaer <notifications@github.com>:

**Comment by mrbeam** [comment]
another hint: 
linear bearings with dry running sealings cause quite some backlash which results in this effect.
-> lubricate the rods.
