### ISSUE TITLE
Software lagging command execution

### ISSUE THREAD

**Issue by mrbeam** [mrbeam/OctoPrint#36]
User wrote:

Hi all,

I have the impression that the software GUI (OctoPi) is lagging in sending commands to the arduino.
If I click a button it takes sometimes 1-3 seconds before the command gets executed.

I'm on the latest update via the GUI.

**Comment by only1pj** [comment]
Plus one for this.
Its not a new issue - had this from day one. 
Seems more of an issue when just booting or just before/after a long process.

**Comment by make-ing** [comment]
This seems to be a problem with the general speed of the Raspberry Pi 1. During boot and short after this the pi is still under heavy load due to all the services starting up and the connections are established. Same holds true for long processes. This will be solved a soon as we switch to RPi3.
