### ISSUE TITLE
Hardware 'Abort' button stops the job but puts machine in an unusable state.  

### ISSUE THREAD

**Issue by mrbeam** [mrbeam/OctoPrint#38]
as headline says. 
Reproduction:
1. start a job
2. press hardware abort button
3. try to start another job

**Comment by make-ing** [comment]
bug was fixed in commit [7c11c04](https://github.com/mrbeam/OctoPrint/commit/7c11c042349f571fd3c23d23e901d5d276a6a79b#diff-f563e4aba47507df56026ef96effd760).
