### ISSUE TITLE
Configured WiFi is blocking AP mode if not present during start.

### ISSUE THREAD

**Issue by mrbeam** [mrbeam/OctoPrint#40]
If there is already a WiFi configured in the Mr Beam webinterface and the Raspberry is booting in a differenct location, the AP mode is not enabled.
Somehow netconnectd tries to log into the recently used WiFi without detecting that it is not reachable.

Possibly a timeout is probably not working as the RPi does not have a correct time via ntp yet.

**Comment by make-ing** [comment]
works perfectly fine on my end :) ... closed
