### ISSUE TITLE
Design library gets rendered only partly

### ISSUE THREAD

**Issue by TopperDEL** [mrbeam/OctoPrint#54]
There seems to be an issue within the latest version. The design library is cut off on top and bottom, so I can't see the full list. It show wrong in IE, Edge and Chrome.
<img width="715" alt="error" src="https://cloud.githubusercontent.com/assets/1833242/11348598/a0b85a60-9227-11e5-9d68-bb716d73b67a.png">

**Comment by TopperDEL** [comment]
I realized this only happens when I'm logged in.

**Comment by mrbeam** [comment]
damn, this is ugly. Reason: your username is too long and causing the whole menu to wrap to the next line. 
Workaround until fix:  use a shorter username.

**Comment by TopperDEL** [comment]
I think I go for "Mr.T"... :)

**Comment by make-ing** [comment]
I can't reproduce it, and i think this was fixed with the commit 43a476e. If you still have problems please comment again and i will reopen this issue. Until then, fixed!

**Comment by make-ing** [comment]
The problem is still present and seems to be font related. Which OS are you using? Windows?

**Comment by amrsoll** [comment]
Is fixed in the plugin now
