### ISSUE TITLE
Image processing preview

### ISSUE THREAD

**Issue by TopperDEL** [mrbeam/OctoPrint#55]
When I slice an image it would be great to see the result with the image I provided.

**Comment by mrbeam** [comment]
for sure! 
The preview is currently faked just to visualize what the sliders are meant for.
Depending on the size of the image a real preview will take too long. Faking that with js or svg filters would work in  theory, but then the result of what happens in the backend is not the same.  
Taking the faked result from the svg filter is not possible right now.

**Comment by TopperDEL** [comment]
That's not a big deal. One gets used to how the result will look like after some cuts.
