### ISSUE TITLE
Weird feedrate behaivour when using feedrate slider

### ISSUE THREAD

**Issue by make-ing** [mrbeam/OctoPrint#60]
When the feedrate slider was at 150% the movement was sometime normal (150%) and sometime very fast (more then 150%).

**Comment by cojarbi** [comment]
Were you doing a raster?  If so the there will be a difference in speed depending on what setting you used for white and black

**Comment by mrbeam** [comment]
fixed with de622e5e8ee9df1294e86f5a2ea3dd60ad70f494

**Comment by mrbeam** [comment]
@cojarbi these sliders affect all intensity and feedrate settings during the streaming. new values are calculated by multiplying with the percentage but the result stays in maximum / minimum bounds.
