### ISSUE TITLE
Filled areas don't match with outline

### ISSUE THREAD

**Issue by make-ing** [mrbeam/OctoPrint#61]
Sometimes the filled areas don't match with the outlines (misalignment).

**Comment by cojarbi** [comment]
Is this and svg? How did you compose it?

**Comment by make-ing** [comment]
The filled areas are bitmaps and the outlines are svg. We probably found the bug... I'm testing at the moment.

**Comment by make-ing** [comment]
Fixed: [commit 1082080](https://github.com/mrbeam/mrbeam-inkscape-ext/commit/10820805b7120ff56a952c1021577a5bfd62c863)
