### ISSUE TITLE
Not loading after upgrade 

### ISSUE THREAD

**Issue by cojarbi** [mrbeam/OctoPrint#62]
Once connected to the Internet, octoprint shows various updates.  Once done it seems configuration is lost. Is this the correct process to upgrade or there I another proper way?

**Comment by make-ing** [comment]
Hello Ariel, can you tell me which configuration is lost?

**Comment by cojarbi** [comment]
@florian. After the update I can not longer connect to the server. It gives me a 503 error. I can ping the nic so I know the OS is up. 

Mind that there where 4 upgrades available octoprint, svg and other 2

Ariel Yahni

**Comment by make-ing** [comment]
Have your tried to do a restart? I never had such a problem and also heard of this the first time.

**Comment by cojarbi** [comment]
Yes. Restarted many times. Is the root user and password the default for octoprint. I want to ssh and sea what's going on. 

I had to reflash the card with the image and start all over bacause of this and did the process all over again with the same result. 

I saw that after upgrading the error bobble on the right that said octoprint failed to restart after the upgrade 

Ariel Yahni

**Comment by cojarbi** [comment]
What's the correct way to update

**Comment by make-ing** [comment]
@cojarbi: Is this problem still unsolved? The correct way would be to click on the "Update Now" if the "Update Available" dialog pops up.

**Comment by cojarbi** [comment]
I have done that many times but haven't doesn't work. Also i get a constsnt lock as I don't have endstops and im unable to relsease

AY

**Comment by make-ing** [comment]
The release Problem without homing is solved. See https://github.com/mrbeam/OctoPrint/issues/65
It is currently not in the stable-1.2.2 branch but in the development mrbeam branch.

Can you tell me your exact setup because i can not reproduce this upgrade behavior on my side.

**Comment by cojarbi** [comment]
Will do, currently testing other firmware so i need to get back to that one

On Thu, Jun 2, 2016 at 11:18 AM, Florian <notifications@github.com> wrote:

> The release Problem without homing is solved. See #65
> <https://github.com/mrbeam/OctoPrint/issues/65>
> It is currently not in the stable-1.2.2 branch but in the development
> mrbeam branch.
>
> Can you tell me your exact setup because i can not reproduce this upgrade
> behavior on my side.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrbeam/OctoPrint/issues/62#issuecomment-223343408>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APrsFqN3brWkc0xj8duNNqvMLaz_Sm4_ks5qHwJcgaJpZM4HO7mZ>
> .
>



-- 

Ariel Yahni

**Comment by make-ing** [comment]
What setup do you have (RPi version, host OS, browser, network connection)?
