### ISSUE TITLE
Change title of update notification

### ISSUE THREAD

**Issue by Gallore** [mrbeam/OctoPrint#64]
Current title says "Update Available". Change it to "Mr Beam Update Available" or something similar so that it's clear for the user that the Update is for Mr Beam. Internet users are facing fake update notifications on a regular basis. Make sure that the user understands that this update notification is about Mr Beam and that it's authentic.
<img width="318" alt="screenshot 2016-05-03 13 58 43" src="https://cloud.githubusercontent.com/assets/4582388/14982608/d4dffba6-1137-11e6-93f3-ac2b8f85fdca.png">

**Comment by Gallore** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9281517-99006813_5-s1-v1.png?palette=1&width=246)

**Comment by make-ing** [comment]
Thank you very much Gallore for this suggestion... I will make the changes with the next update

**Comment by make-ing** [comment]
This enhancement will come to stable with the next update.
