### ISSUE TITLE
Homing disabled but still locked

### ISSUE THREAD

**Issue by cojarbi** [mrbeam/OctoPrint#65]
I have latest MrBeam Image and GRBL. I cannot unlock the machine. My $22 is 0. 
I did $X it says OK but when i return to the work screen its still locked asking me to Home

**Comment by make-ing** [comment]
This is very machine specific and currently our software does not support this. I will label this as enhancement, but don't expect us to come to this very soon.

**Comment by make-ing** [comment]
added functionality with commit 2c416ea in mrbeam branch. This will be testet and added to the stable-1.2.2 branch on the next big update.

**Comment by make-ing** [comment]
added functionality with commit 2c416ea in mrbeam branch. This will be testet and added to the stable-1.2.2 branch on the next big update.
