### ISSUE TITLE
Don't remove svg text elements, just display warning in conversion dialog.

### ISSUE THREAD

**Issue by hungerpirat** [mrbeam/OctoPrint#66]
Currently all text elements are removed and there is a global warning popup telling this. 
As engraving infills can handle text elements quite fine and only cutting outlines is not possible, the elements should not be removed. Additionally the warning should not be displayed after placing the svg on the working area - it should be done inside the conversion dialog.

**Comment by clemniem** [comment]
Fixed with previous commit.
