### ISSUE TITLE
New Home

### ISSUE THREAD

**Issue by only1pj** [mrbeam/OctoPrint#7]
#enhancement
I dont know how to add labels!!!

Currently the X0/Y0 home is fixed. Pressing the House icon brings the laser back "home".

Materials to be marked/cut currently have to be placed manually at 0/0 or the job has to be run with a low power beam in order to see where the start point might be and then place the material at the relevant coordinate.

Even jobs with graphics/text to be engraved at 0/0 have started at seemingly random locations before now (for me anyway).

If the laser was manually moved to a specific location, over the exact point at which the user wishes to start the engraving, and a "set this as home" button was pressed, this point should become the start point for a job ensuring that the material is marked exactly, first time.

Home should still be X0/Y0
Manually assigned home can be anywhere within the working area.

PJ

**Comment by hungerpirat** [comment]
works

**Comment by mrbeam** [comment]
implemented in 901e63a (branch mrbeam-ui)
