### ISSUE TITLE
Size of placed object does not match original source

### ISSUE THREAD

**Issue by Quasimondo** [mrbeam/OctoPrint#70]
When placing an SVG (exported from Illustrator as SVG 1.0 format) the scale does not match the original size, it rather gets scaled down to something around 90% of the source - so it requires 1 step of CTRL-limited scaling with the handle to rescale it to the desired size.

**Comment by make-ing** [comment]
commit f486a24 now allows for changing the SVG dpi in the settings menu. For SVG's made with Illustrator use 72 dpi and for SVG's made with inkscape use 90 dpi. The commit will be added to the stable branch on next update.
