### ISSUE TITLE
<switch> tag is ignored

### ISSUE THREAD

**Issue by hungerpirat** [mrbeam/OctoPrint#85]
A SVG file generated with Illustrator contained the <switch> tag for unknown reason. 
Everything inside was ignored. 

Figure out what <switch> does and treat content accordingly.

**Comment by clemniem** [comment]
switch tag was checking for installed AI Plugin. The Plugin was not installed and thats why switch jumped over the assigned g element in svg.

**Comment by amrsoll** [comment]
Referenced in mrbeam/MrBeamPlugin#643
