### ISSUE TITLE
Background image embedded in GCode even if not engraving anything.

### ISSUE THREAD

**Issue by hungerpirat** [mrbeam/OctoPrint#86]
Generated GCode starts with 

`;Generated from temp.svg f824111a8fd96e3794c382f054e60846ca202289
G21

;Image: 499.90x399.90 @ 0.10,-0.10| data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAE4cAAA+fCAYAAAASPhjfAAAgAElEQVR4XuzcMREAAAgDMfBvGhn8EBT0UubuOAIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBB4F9j3BAIQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECxuH8AAECBAgQIECAAAECBA
gQIECAAAECBAgQIECAAAEC...
...

;self.beam = 0.20
;pierce_time = 0.000s
;intensity_black = 500.00
;intensity_white = 0.00
;feedrate_white = 1500.00
;feedrate_black = 250.00
;material = default
;contrastFactor = 1.00
;sharpeningFactor = 1.00
;dithering = False
F1500
M3S0
;EndImage
M5

; Layer: gSiuhawct9fu, outline of rectSiuhawct9fv
G0 X270.6693 Y192.7099

M03 S950
G01 F125.000000
G01  X289.6906 Y211.5528
G01  X308.5335 Y192.5315
G01  X289.5122 Y173.6886
G01  X270.6693 Y192.7099
M03 S0

M05
`

**Comment by clemniem** [comment]
fixed
